name: MyPlugin
main: net.mypackage.myplugin.MyPlugin
version: 1.0.0
author: <your name>
team: <your team, optional>
description: "Put your description here"
license: MIT
website: http://www.myhomepage.com